//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutorial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tutorial()
        {
            this.Paso = new HashSet<Paso>();
        }
    
        public int Id { get; set; }
        public string Titulo { get; set; }
        public Nullable<bool> Featured { get; set; }
        public string Video { get; set; }
        public string Descripcion { get; set; }
        public string Dificultad { get; set; }
        public string Tiempo { get; set; }
        public string Imagen { get; set; }
        public Nullable<System.DateTime> Publicacion { get; set; }
        public Nullable<int> SeccionId { get; set; }
    
        public virtual Seccion Seccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paso> Paso { get; set; }
    }
}
